version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    groups:
      ruby-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    groups:
      node-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    groups:
      delivery-images:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    groups:
      development-images:
        patterns:
          - "*"
